INSERT INTO
  `ingredient_category` (ingredient_category_name)
VALUES
('APPLEBEE''S'),
('ARCHWAY Home Style Cookies'),
('AUSTIN'),
('Abiyuch'),
('Acerola'),
('Acerola juice'),
('Acorn stew'),
('Agave'),
('Agutuk'),
('Alcoholic beverage'),
('Alfalfa seeds'),
('Amaranth grain'),
('Amaranth leaves'),
('Animal fat'),
('Apple juice'),
('Apples'),
('Applesauce'),
('Apricot nectar'),
('Apricots'),
('Arrowhead'),
('Arrowroot'),
('Arrowroot flour'),
('Artichokes'),
('Artificial Blueberry Muffin Mix'),
('Arugula'),
('Ascidians'),
('Asparagus'),
('Avocados'),
('BARBARA DEE'),
('BEAR NAKED'),
('BURGER KING'),
('BUTCHER BOY MEATS'),
('Baby food'),
('Babyfood'),
('Bacon'),
('Bacon and beef sticks'),
('Bacon bits'),
('Bagel'),
('Bagels'),
('Baking chocolate'),
('Balsam-pear'),
('Bamboo shoots'),
('Bananas'),
('Barbecue loaf'),
('Barley'),
('Barley flour or meal'),
('Barley malt flour'),
('Basil'),
('Bean beverage'),
('Beans'),
('Bear'),
('Beef'),
('Beef Pot Pie'),
('Beef broth and tomato juice'),
('Beef macaroni with tomato sauce'),
('Beef sausage'),
('Beef stew'),
('Beerwurst'),
('Beet greens'),
('Beets'),
('Beverage'),
('Beverages'),
('Biscuits'),
('Bison'),
('Blackberries'),
('Blackberry juice'),
('Blood sausage'),
('Blueberries'),
('Bockwurst'),
('Bologna'),
('Borage'),
('Boysenberries'),
('Bratwurst'),
('Braunschweiger'),
('Bread'),
('Bread crumbs'),
('Bread sticks'),
('Bread stuffing'),
('Breadfruit'),
('Breakfast bar'),
('Breakfast bars'),
('Breakfast tart'),
('Broadbeans'),
('Broccoli'),
('Broccoli raab'),
('Brotwurst'),
('Brussels sprouts'),
('Buckwheat'),
('Buckwheat flour'),
('Buckwheat groats'),
('Buffalo'),
('Bulgur'),
('Burdock root'),
('Burrito'),
('Butter'),
('Butter oil'),
('Butter replacement'),
('Butterbur'),
('CAMPBELL''S'),
('CAMPBELL''S Au Jus Gravy'),
('CAMPBELL''S Beef Gravy'),
('CAMPBELL''S Brown Gravy with Onions'),
('CAMPBELL''S CHUNKY'),
('CAMPBELL''S CHUNKY Microwavable Bowls'),
('CAMPBELL''S CHUNKY Soups'),
('CAMPBELL''S Chicken Gravy'),
('CAMPBELL''S Country Style Cream Gravy'),
('CAMPBELL''S Country Style Sausage Gravy'),
('CAMPBELL''S Fat Free Beef Gravy'),
('CAMPBELL''S Fat Free Chicken Gravy'),
('CAMPBELL''S Fat Free Turkey Gravy'),
('CAMPBELL''S Golden Pork Gravy'),
('CAMPBELL''S HEALTHY REQUEST'),
('CAMPBELL''S Homestlye Light New England Clam Chowder'),
('CAMPBELL''S Homestyle Butternut Squash Bisque'),
('CAMPBELL''S Homestyle Chicken with White & Wild Rice Soup'),
('CAMPBELL''S Homestyle HEALTHY REQUEST Chicken with Whole Grain Pasta Soup'),
('CAMPBELL''S Homestyle HEALTHY REQUEST Mexican Style Chicken Tortilla'),
('CAMPBELL''S Homestyle Harvest Tomato with Basil Soup'),
('CAMPBELL''S Homestyle Italian-Style Wedding Soup'),
('CAMPBELL''S Homestyle Light Italian-Style Wedding Soup'),
('CAMPBELL''S Homestyle Mexican Style Chicken Tortilla Soup'),
('CAMPBELL''S Homestyle Microwaveable Bowls'),
('CAMPBELL''S Homestyle Minestrone Soup'),
('CAMPBELL''S Homestyle New England Clam Chowder'),
('CAMPBELL''S Homestyle Potato Broccoli Cheese Soup'),
('CAMPBELL''S Homestyle Vegetable Medley Soup'),
('CAMPBELL''S Low Sodium Soups'),
('CAMPBELL''S Microwavable Beef Gravy'),
('CAMPBELL''S Microwavable Chicken Gravy'),
('CAMPBELL''S Microwavable Turkey Gravy'),
('CAMPBELL''S Mushroom Gravy'),
('CAMPBELL''S Red and White'),
('CAMPBELL''S Red and White - Microwaveable Bowls'),
('CAMPBELL''S Soup on the Go'),
('CAMPBELL''S Turkey Gravy'),
('CARL BUDDIG'),
('CARL BUDDIG. Cooked Smoked Beef Pastrami'),
('CARRABBA''S ITALIAN GRILL'),
('CHICK-FIL-A'),
('CONTINENTAL MILLS'),
('CRACKER BARREL'),
('Cabbage'),
('Cake'),
('Cake mix'),
('Campbell''s Brown Sugar And Bacon Flavored Baked Beans'),
('Campbell''s Pork and Beans'),
('Canada Goose'),
('Canadian bacon'),
('Candied fruit'),
('Candies'),
('Capers'),
('Carambola'),
('Carbonated beverage'),
('Cardoon'),
('Caribou'),
('Carissa'),
('Carob flour'),
('Carob-flavor beverage mix'),
('Carrot'),
('Carrot juice'),
('Carrots'),
('Cassava'),
('Catsup'),
('Cattail'),
('Cauliflower'),
('Celeriac'),
('Celery'),
('Celery flakes'),
('Celtuce'),
('Cereals'),
('Cereals ready-to-eat'),
('Chard'),
('Chayote'),
('Cheese'),
('Cheese food'),
('Cheese product'),
('Cheese puffs and twists'),
('Cheese sauce'),
('Cheese spread'),
('Cheese substitute'),
('Cheesecake commercially prepared'),
('Cheesecake prepared from mix'),
('Cheesefurter'),
('Cherimoya'),
('Cherries'),
('Chewing gum'),
('Chicken'),
('Chicken breast'),
('Chicken breast tenders'),
('Chicken patty'),
('Chicken pot pie'),
('Chicken roll'),
('Chicken spread'),
('Chicken tenders'),
('Chickpea flour'),
('Chickpeas'),
('Chicory'),
('Chicory greens'),
('Chicory roots'),
('Chilchen'),
('Child formula'),
('Chili'),
('Chili con carne with beans'),
('Chili with beans'),
('Chiton'),
('Chives'),
('Chocolate'),
('Chocolate syrup'),
('Chocolate-flavor beverage mix'),
('Chocolate-flavor beverage mix for milk'),
('Chocolate-flavored drink'),
('Chocolate-flavored hazelnut spread'),
('Chokecherries'),
('Chorizo'),
('Chrysanthemum'),
('Chrysanthemum leaves'),
('Cinnamon buns'),
('Citrus fruit juice drink'),
('Clam and tomato juice'),
('Clementines'),
('Cloudberries'),
('Cockles'),
('Cocktail mix'),
('Cocoa'),
('Cocoa mix'),
('Coffee'),
('Coffee and cocoa  powder'),
('Coffee substitute'),
('Coffeecake'),
('Collards'),
('Cookie'),
('Cookies'),
('Coriander  leaves'),
('Corn'),
('Corn bran'),
('Corn dogs'),
('Corn flour'),
('Corn grain'),
('Corn pudding'),
('Corn with red and green peppers'),
('Corned beef and potatoes in tortilla'),
('Corned beef loaf'),
('Cornmeal'),
('Cornsalad'),
('Cornstarch'),
('Couscous'),
('Cowpeas'),
('Crabapples'),
('Cracker meal'),
('Crackers'),
('Cranberries'),
('Cranberry'),
('Cranberry juice'),
('Cranberry juice cocktail'),
('Cranberry sauce'),
('Cranberry-apple juice drink'),
('Cranberry-apricot juice drink'),
('Cranberry-grape juice drink'),
('Cranberry-orange relish'),
('Cream'),
('Cream puff'),
('Cream puff shell'),
('Cream substitute'),
('Creamy dressing'),
('Cress'),
('Croissants'),
('Croutons'),
('Crustaceans'),
('Cucumber'),
('Currants'),
('Custard-apple'),
('DENNY''S'),
('DIGIORNO Pizza'),
('DOMINO''S 14" Cheese Pizza'),
('DOMINO''S 14" EXTRAVAGANZZA FEAST Pizza'),
('DOMINO''S 14" Pepperoni Pizza'),
('DOMINO''S 14" Sausage Pizza'),
('Dairy'),
('Dairy drink mix'),
('Dandelion greens'),
('Danish pastry'),
('Dates'),
('Deer'),
('Dessert topping'),
('Desserts'),
('Dill weed'),
('Dip'),
('Dock'),
('Doughnuts'),
('Dove'),
('Dressing'),
('Drink mix'),
('Drumstick leaves'),
('Drumstick pods'),
('Duck'),
('Dulce de Leche'),
('Durian'),
('Dutch brand loaf'),
('Edamame'),
('Egg'),
('Egg Mix'),
('Egg custards'),
('Egg rolls'),
('Egg substitute'),
('Eggnog'),
('Eggnog-flavor mix'),
('Eggplant'),
('Eggs'),
('Elderberries'),
('Elk'),
('Emu'),
('Endive'),
('Energy drink'),
('English muffins'),
('Entrees'),
('Epazote'),
('Eppaw'),
('FAMOUS AMOS'),
('FRANCO-AMERICAN Fat Free Slow Roast Beef Gravy'),
('FRANCO-AMERICAN Fat Free Slow Roast Chicken Gravy'),
('FRANCO-AMERICAN Slow Roast Beef Gravy'),
('FRANCO-AMERICAN Slow Roast Chicken Gravy'),
('FRANCO-AMERICAN Slow Roast Turkey Gravy'),
('Falafel'),
('Fast food'),
('Fast foods'),
('Fat'),
('Fat free ice cream'),
('Feijoa'),
('Fennel'),
('Fiddlehead ferns'),
('Figs'),
('Fireweed'),
('Fish'),
('Fish broth'),
('Fish oil'),
('Fish sticks'),
('Flan'),
('Fluid replacement'),
('Focaccia'),
('Formulated bar'),
('Frankfurter'),
('French toast'),
('Frijoles rojos volteados'),
('Frog legs'),
('Frostings'),
('Frozen novelties'),
('Frozen yogurts'),
('Fruit butters'),
('Fruit cocktail'),
('Fruit flavored drink'),
('Fruit flavored drink containing less than 3% fruit juice'),
('Fruit juice drink'),
('Fruit punch drink'),
('Fruit punch juice drink'),
('Fruit punch-flavor drink'),
('Fruit salad'),
('Fruit-flavored drink'),
('Frybread'),
('Fungi'),
('GARDENBURGER Black Bean Chipotle Burger'),
('GARDENBURGER Flame Grilled Burger'),
('GARDENBURGER Original'),
('GARDENBURGER Savory Portabella Veggie Burger'),
('GARDENBURGER Sun-Dried Tomato Basil Burger'),
('GARDENBURGER Veggie Medley Burger'),
('GENERAL MILLS'),
('GEORGE WESTON BAKERIES'),
('GIRL SCOUTS'),
('Game meat'),
('Garlic'),
('Garlic bread'),
('Gelatin desserts'),
('Gelatins'),
('Ginger root'),
('Goat'),
('Goose'),
('Gooseberries'),
('Gourd'),
('Granola bar'),
('Grape drink'),
('Grape juice'),
('Grape juice drink'),
('Grape leaves'),
('Grapefruit'),
('Grapefruit juice'),
('Grapes'),
('Gravy'),
('Ground turkey'),
('Groundcherries'),
('Guanabana nectar'),
('Guava nectar'),
('Guava sauce'),
('Guavas'),
('Guinea hen'),
('Gums'),
('HEALTHY REQUEST'),
('HEALTHY REQUEST Tomato juice'),
('HEINZ'),
('HORMEL'),
('HORMEL ALWAYS TENDER'),
('HORMEL Canadian Style Bacon'),
('HORMEL Pillow Pak Sliced Turkey Pepperoni'),
('HORMEL SPAM'),
('HORMEL WRANGLER Beef Franks'),
('HOT POCKETS'),
('HOT POCKETS Ham ''N Cheese Stuffed Sandwich'),
('HOUSE FOODS Premium Firm Tofu'),
('HOUSE FOODS Premium Soft Tofu'),
('Ham'),
('Ham and cheese loaf or roll'),
('Ham and cheese spread'),
('Ham salad spread'),
('Hazelnuts'),
('Headcheese'),
('Hearts of palm'),
('Hibiscus tea'),
('Hominy'),
('Honey'),
('Honey roll sausage'),
('Horned melon'),
('Horseradish'),
('Huckleberries'),
('Hummus'),
('Hush puppies'),
('Hyacinth beans'),
('Hyacinth-beans'),
('INTERSTATE BRANDS CORP'),
('Ice cream'),
('Ice cream bar'),
('Ice cream cone'),
('Ice cream cones'),
('Ice cream cookie sandwich'),
('Ice cream sandwich'),
('Ice creams'),
('Imitation cheese'),
('Incaparina'),
('Infant formula'),
('JACKSON''S'),
('Jackfruit'),
('Jams and preserves'),
('Java-plum'),
('Jellies'),
('Jellyfish'),
('Jerusalem-artichokes'),
('Jew''s ear'),
('Juice'),
('Juice Smoothie'),
('Jujube'),
('Jute'),
('KASHI'),
('KASHI Black Bean Mango'),
('KASHI Mayan Harvest Bake'),
('KASHI Mushroom & Asparagus Risotto'),
('KASHI Pesto Pasta Primavera'),
('KASHI Pizza'),
('KASHI Spicy Black Bean Enchilada'),
('KASHI Spinach Artichoke Pasta'),
('KASHI Three Cheese Penne'),
('KASHI Three Cheese Ravioli with Mediterranean Tomato Sauce'),
('KEEBLER'),
('KELLOGG'),
('KELLOGG Mini-Wheats Frosted Bite Size Touch of Fruit Raisin'),
('KELLOGG''S'),
('KELLOGG''S Eggo Lowfat Blueberry Nutri-Grain Waffles'),
('KFC'),
('KRAFT'),
('KRAFT BREAKSTONE''S FREE Fat Free Sour Cream'),
('KRAFT BREAKSTONE''S Reduced Fat Sour Cream'),
('KRAFT CHEEZ WHIZ LIGHT Pasteurized Process Cheese Product'),
('KRAFT CHEEZ WHIZ Pasteurized Process Cheese Sauce'),
('KRAFT FOODS'),
('KRAFT FREE Singles American Nonfat Pasteurized Process Cheese Product'),
('KRAFT VELVEETA LIGHT Reduced Fat Pasteurized Process Cheese Product'),
('KRAFT VELVEETA Pasteurized Process Cheese Spread'),
('Kale'),
('Kanpyo'),
('Keikitos'),
('Kielbasa'),
('Kiwifruit'),
('Knackwurst'),
('Kohlrabi'),
('Kumquats'),
('LEAN POCKETS'),
('LITTLE CAESARS 14" Cheese Pizza'),
('LITTLE CAESARS 14" Original Round Cheese Pizza'),
('LITTLE CAESARS 14" Original Round Meat and Vegetable Pizza'),
('LITTLE CAESARS 14" Original Round Pepperoni Pizza'),
('LITTLE CAESARS 14" Pepperoni Pizza'),
('LOMA LINDA Big Franks'),
('LOMA LINDA Linketts'),
('LOMA LINDA Little Links'),
('LOMA LINDA Low Fat Big Franks'),
('LOMA LINDA Redi-Burger'),
('LOMA LINDA Swiss Stake with Gravy'),
('LOMA LINDA Tender Bits'),
('LOMA LINDA Tender Rounds with Gravy'),
('LOMA LINDA Vege-Burger'),
('LOUIS RICH'),
('Lamb'),
('Lambs quarters'),
('Lambsquarters'),
('Lard'),
('Lasagna'),
('Lasagna with meat & sauce'),
('Lasagna with meat sauce'),
('Leavening agents'),
('Lebanon bologna'),
('Leeks'),
('Lemon grass'),
('Lemon juice'),
('Lemon peel'),
('Lemonade'),
('Lemonade-flavor drink'),
('Lemons'),
('Lentils'),
('Lettuce'),
('Light Ice Cream'),
('Lima beans'),
('Lime juice'),
('Limeade'),
('Limes'),
('Litchis'),
('Liver cheese'),
('Liver sausage'),
('Liverwurst spread'),
('Loganberries'),
('Longans'),
('Loquats'),
('Lotus root'),
('Luncheon meat'),
('Luncheon sausage'),
('Luncheon slices'),
('Lupins'),
('Luxury loaf'),
('MARTHA WHITE FOODS'),
('MCKEE BAKING'),
('MISSION FOODS'),
('MORI-NU'),
('MORNINGSTAR FARMS Asian Veggie Patties'),
('MORNINGSTAR FARMS BBQ Riblets'),
('MORNINGSTAR FARMS Bacon'),
('MORNINGSTAR FARMS Breakfast Bacon Strips'),
('MORNINGSTAR FARMS Breakfast Biscuit Sausage'),
('MORNINGSTAR FARMS Breakfast Pattie'),
('MORNINGSTAR FARMS Breakfast Pattie with Organic Soy'),
('MORNINGSTAR FARMS Breakfast Sausage Links'),
('MORNINGSTAR FARMS Breakfast Sausage Patties'),
('MORNINGSTAR FARMS Breakfast Sausage Patties Maple Flavored'),
('MORNINGSTAR FARMS Buffalo Chik Patties'),
('MORNINGSTAR FARMS Buffalo Wings'),
('MORNINGSTAR FARMS California Turk''y Burger'),
('MORNINGSTAR FARMS Chik Patties'),
('MORNINGSTAR FARMS Chik Patties Original'),
('MORNINGSTAR FARMS Chik''n Grill Veggie Patties'),
('MORNINGSTAR FARMS Chik''n Nuggets'),
('MORNINGSTAR FARMS Corn Dog'),
('MORNINGSTAR FARMS Corn Dog Mini'),
('MORNINGSTAR FARMS Entree Chik''n Enchilada with Rice'),
('MORNINGSTAR FARMS Entree Chili'),
('MORNINGSTAR FARMS Garden Veggie Patties'),
('MORNINGSTAR FARMS Grillers Burger Style Recipe Crumbles'),
('MORNINGSTAR FARMS Grillers Chik''n Veggie Patties'),
('MORNINGSTAR FARMS Grillers Original'),
('MORNINGSTAR FARMS Grillers Prime'),
('MORNINGSTAR FARMS Grillers Quarter Pound Veggie Burger'),
('MORNINGSTAR FARMS Grillers Vegan'),
('MORNINGSTAR FARMS Hot and Spicy Veggie Sausage Patties'),
('MORNINGSTAR FARMS Italian Herb Chik''n Pattie'),
('MORNINGSTAR FARMS Lasagna with Veggie Sausage'),
('MORNINGSTAR FARMS Meal Starters Veggie Meatballs'),
('MORNINGSTAR FARMS Mediterranean Chickpea'),
('MORNINGSTAR FARMS Mushroom Lover''s Burger'),
('MORNINGSTAR FARMS Parmesan Garlic Wings'),
('MORNINGSTAR FARMS Pizza'),
('MORNINGSTAR FARMS Roasted Garlic & Quinoa Burger'),
('MORNINGSTAR FARMS Sausage Style Recipe Crumbles'),
('MORNINGSTAR FARMS Sesame Chik''n Entree'),
('MORNINGSTAR FARMS Spicy Black Bean Burger'),
('MORNINGSTAR FARMS Tomato & Basil Pizza Burger'),
('MORNINGSTAR FARMS Veggie Dog'),
('MORNINGSTAR FARMS Veggie Italian Style Sausage'),
('MORNINGSTAR FARMS Veggie Sweet and Sour Chik''n'),
('MOTHER''S'),
('MURRAY'),
('Macaroni'),
('Macaroni and Cheese'),
('Macaroni and cheese dinner with dry sauce mix'),
('Macaroni and cheese loaf'),
('Macaroni or noodles with cheese'),
('Malabar spinach'),
('Malt beverage'),
('Malted drink mix'),
('Mammy-apple'),
('Mango nectar'),
('Mangos'),
('Mangosteen'),
('Maraschino cherries'),
('Margarine'),
('Margarine Spread'),
('Margarine-like'),
('Margarine-like shortening'),
('Margarine-like spread'),
('Margarine-like spread with yogurt'),
('Margarine-like vegetable-oil spread'),
('Marmalade'),
('Mashu roots'),
('Mayonnaise'),
('Mayonnaise dressing'),
('McDONALD''S'),
('McDONALD''S Bacon Ranch Salad with Crispy Chicken'),
('Meal supplement drink'),
('Meat drippings'),
('Meat extender'),
('Meatballs'),
('Melon'),
('Melon balls'),
('Melons'),
('Milk'),
('Milk and cereal bar'),
('Milk dessert'),
('Milk dessert bar'),
('Milk shakes'),
('Milk substitutes'),
('Millet'),
('Millet flour'),
('Miso'),
('Mixed vegetable and fruit juice drink'),
('Molasses'),
('Mollusks'),
('Moose'),
('Mortadella'),
('Mothbeans'),
('Mother''s loaf'),
('Mountain yam'),
('Mouse nuts'),
('Muffin'),
('Muffins'),
('Mulberries'),
('Mung beans'),
('Mungo beans'),
('Mush'),
('Mushrooms'),
('Mustard'),
('Mustard greens'),
('Mustard spinach'),
('Mutton'),
('NABISCO'),
('Nance'),
('Naranjilla  pulp'),
('Natto'),
('Nectarines'),
('New Zealand spinach'),
('New england brand sausage'),
('Noodles'),
('Nopales'),
('Nutritional supplement for people with diabetes'),
('Nuts'),
('OLIVE GARDEN'),
('ON THE BORDER'),
('OSCAR MAYER'),
('OSCAR MAYER. Bologna'),
('Oat bran'),
('Oat flour'),
('Oats'),
('Octopus'),
('Oheloberries'),
('Oil'),
('Okara'),
('Okra'),
('Olive loaf'),
('Olives'),
('Onion rings'),
('Onions'),
('Oopah'),
('Orange Pineapple Juice Blend'),
('Orange and apricot juice drink'),
('Orange breakfast drink'),
('Orange drink'),
('Orange juice'),
('Orange juice drink'),
('Orange peel'),
('Orange-flavor drink'),
('Orange-grapefruit juice'),
('Oranges'),
('Ostrich'),
('Oven-roasted chicken breast roll'),
('Owl'),
('P REGO Pasta'),
('PACE'),
('PAPA JOHN''S 14" Cheese Pizza'),
('PAPA JOHN''S 14" Pepperoni Pizza'),
('PAPA JOHN''S 14" The Works Pizza'),
('PILLSBURY'),
('PILLSBURY GRANDS'),
('PILLSBURY Golden Layer Buttermilk Biscuits'),
('PIZZA HUT 12" Cheese Pizza'),
('PIZZA HUT 12" Pepperoni Pizza'),
('PIZZA HUT 12" Super Supreme Pizza'),
('PIZZA HUT 14" Cheese Pizza'),
('PIZZA HUT 14" Pepperoni Pizza'),
('PIZZA HUT 14" Sausage Pizza'),
('PIZZA HUT 14" Super Supreme Pizza'),
('POPEYES'),
('PREGO Pasta'),
('Pan Dulce'),
('Pancakes'),
('Pancakes plain'),
('Papad'),
('Papaya'),
('Papaya nectar'),
('Papayas'),
('Parmesan cheese topping'),
('Parsley'),
('Parsnips'),
('Passion-fruit'),
('Passion-fruit juice'),
('Pasta'),
('Pasta mix'),
('Pasta with Sliced Franks in Tomato Sauce'),
('Pasta with tomato sauce'),
('Pastrami'),
('Pastry'),
('Pate'),
('Pate de foie gras'),
('Peach nectar'),
('Peaches'),
('Peanut butter'),
('Peanut butter with omega-3'),
('Peanut flour'),
('Peanut spread'),
('Peanuts'),
('Pear nectar'),
('Pears'),
('Peas'),
('Peas and carrots'),
('Peas and onions'),
('Pectin'),
('Pepeao'),
('Pepper'),
('Peppered loaf'),
('Peppermint'),
('Pepperoni'),
('Peppers'),
('Persimmons'),
('Pheasant'),
('Phyllo dough'),
('Pickle and pimiento loaf'),
('Pickle relish'),
('Pickles'),
('Picnic loaf'),
('Pie'),
('Pie crust'),
('Pie fillings'),
('Pigeon peas'),
('Pigeonpeas'),
('Piki bread'),
('Pimento'),
('Pineapple'),
('Pineapple and grapefruit juice drink'),
('Pineapple and orange juice drink'),
('Pineapple juice'),
('Pinon Nuts'),
('Pitanga'),
('Pizza'),
('Pizza rolls'),
('Plantains'),
('Plums'),
('Poi'),
('Pokeberry shoots'),
('Polish sausage'),
('Pomegranate juice'),
('Pomegranates'),
('Popcorn'),
('Popovers'),
('Pork'),
('Pork and beef sausage'),
('Pork and turkey sausage'),
('Pork loin'),
('Pork sausage'),
('Pork sausage rice links'),
('Potato chips'),
('Potato flour'),
('Potato pancakes'),
('Potato puffs'),
('Potato salad'),
('Potato salad with egg'),
('Potato soup'),
('Potatoes'),
('Potsticker or wonton'),
('Poultry'),
('Poultry salad sandwich spread'),
('Prairie Turnips'),
('Pretzels'),
('Prickly pears'),
('Protein supplement'),
('Prune juice'),
('Prune puree'),
('Prunes'),
('Pudding'),
('Puddings'),
('Puff pastry'),
('Pulled pork in barbecue sauce'),
('Pummelo'),
('Pumpkin'),
('Pumpkin flowers'),
('Pumpkin leaves'),
('Pumpkin pie mix'),
('Purslane'),
('Quail'),
('Queso cotija'),
('Quinces'),
('Quinoa'),
('Radicchio'),
('Radish seeds'),
('Radishes'),
('Raisins'),
('Rambutan'),
('Raspberries'),
('Ravioli'),
('Ready-to-drink reduced fat milk beverage'),
('Reddi Wip Fat Free Whipped Topping'),
('Refried beans'),
('Rennin'),
('Restaurant'),
('Rhubarb'),
('Rice'),
('Rice and Wheat cereal bar'),
('Rice and vermicelli mix'),
('Rice bowl with chicken'),
('Rice bran'),
('Rice cake'),
('Rice drink'),
('Rice flour'),
('Rice noodles'),
('Roast beef'),
('Roast beef spread'),
('Rolls'),
('Rose Hips'),
('Rose-apples'),
('Roselle'),
('Rosemary'),
('Rowal'),
('Ruffed Grouse'),
('Rutabagas'),
('Rye flour'),
('Rye grain'),
('SILK Banana-Strawberry soy yogurt'),
('SILK Black Cherry soy yogurt'),
('SILK Blueberry soy yogurt'),
('SILK Chai'),
('SILK Chocolate'),
('SILK Coffee'),
('SILK French Vanilla Creamer'),
('SILK Hazelnut Creamer'),
('SILK Key Lime soy yogurt'),
('SILK Light Chocolate'),
('SILK Light Plain'),
('SILK Light Vanilla'),
('SILK Mocha'),
('SILK Nog'),
('SILK Original Creamer'),
('SILK Peach soy yogurt'),
('SILK Plain'),
('SILK Plain soy yogurt'),
('SILK Plus Fiber'),
('SILK Plus Omega-3 DHA'),
('SILK Plus for Bone Health'),
('SILK Raspberry soy yogurt'),
('SILK Strawberry soy yogurt'),
('SILK Unsweetened'),
('SILK Vanilla'),
('SILK Vanilla soy yogurt'),
('SILK Very Vanilla'),
('SMART SOUP'),
('SPAGHETTIOS'),
('SUBWAY'),
('SUNSHINE'),
('SUPPER BAKES MEAL KITS'),
('SWANSON'),
('SWANSON BROTH'),
('Salad dressing'),
('Salami'),
('Salmon'),
('Salmonberries'),
('Salsify'),
('Salt'),
('Sandwich spread'),
('Sapodilla'),
('Sapote'),
('Sauce'),
('Sauerkraut'),
('Sausage'),
('School Lunch Pizza'),
('Scrapple'),
('Sea cucumber'),
('Sea lion'),
('Seal'),
('Seasoning mix'),
('Seaweed'),
('Seeds'),
('Semolina'),
('Sesbania flower'),
('Shake'),
('Shallots'),
('Sherbet'),
('Shortening'),
('Shortening bread'),
('Shortening cake mix'),
('Shortening confectionery'),
('Shortening frying'),
('Shortening household soybean  and palm'),
('Shortening industrial'),
('Side dishes'),
('Smelt'),
('Smoked link sausage'),
('Snack'),
('Snacks'),
('Sorghum flour'),
('Sorghum grain'),
('Soup'),
('Sour cream'),
('Sour dressing'),
('Sourdock'),
('Soursop'),
('Soy flour'),
('Soy meal'),
('Soy protein concentrate'),
('Soy protein isolate'),
('Soy sauce'),
('Soy sauce made from hydrolyzed vegetable protein'),
('Soy sauce made from soy'),
('Soy sauce made from soy and wheat'),
('Soybean'),
('Soybeans'),
('Soymilk'),
('Spaghetti'),
('Spaghetti with meat sauce'),
('Spanish rice mix'),
('Spearmint'),
('Spelt'),
('Spices'),
('Spinach'),
('Spinach souffle'),
('Split pea soup'),
('Split pea with ham soup'),
('Squab'),
('Squash'),
('Squirrel'),
('Steelhead trout'),
('Stew'),
('Stew/soup'),
('Stinging Nettles'),
('Strawberries'),
('Strawberry-flavor beverage mix'),
('Strudel'),
('Succotash'),
('Sugar'),
('Sugar-apples'),
('Sugars'),
('Swamp cabbage'),
('Sweet Potato puffs'),
('Sweet Potatoes'),
('Sweet potato'),
('Sweet potato leaves'),
('Sweet rolls'),
('Sweetener'),
('Sweeteners'),
('Swisswurst'),
('Syrup'),
('Syrups'),
('T.G.I. FRIDAY''S'),
('TACO BELL'),
('Taco shells'),
('Tamales'),
('Tamarind nectar'),
('Tamarinds'),
('Tangerine juice'),
('Tangerines'),
('Tapioca'),
('Taquitos'),
('Taro'),
('Taro leaves'),
('Taro shoots'),
('Tea'),
('Teff'),
('Tempeh'),
('Tennis Bread'),
('Thuringer'),
('Thyme'),
('Toaster pastries'),
('Toddler formula'),
('Tofu'),
('Tofu yogurt'),
('Tomatillos'),
('Tomato and vegetable juice'),
('Tomato juice'),
('Tomato powder'),
('Tomato products'),
('Tomato sauce'),
('Tomatoes'),
('Toppings'),
('Tortellini'),
('Tortilla'),
('Tortilla chips'),
('Tortillas'),
('Tostada shells'),
('Tostada with guacamole'),
('Tree fern'),
('Triticale'),
('Triticale flour'),
('Turkey'),
('Turkey Pot Pie'),
('Turkey and gravy'),
('Turkey and pork sausage'),
('Turkey bacon'),
('Turkey breast'),
('Turkey from whole'),
('Turkey ham'),
('Turkey patties'),
('Turkey roast'),
('Turkey roll'),
('Turkey sausage'),
('Turkey sticks'),
('Turkey thigh'),
('Turnip greens'),
('Turnip greens and turnips'),
('Turnips'),
('Turnover'),
('Turtle'),
('USDA Commodity'),
('USDA Commodity Chicken'),
('USDA Commodity Food'),
('USDA Commodity peaches'),
('USDA Commodity pears'),
('V8 SPLASH Juice Drinks'),
('V8 SPLASH Smoothies'),
('V8 V. FUSION Juices'),
('Vanilla extract'),
('Veal'),
('Vegetable and fruit juice drink'),
('Vegetable juice cocktail'),
('Vegetable oil'),
('Vegetable oil-butter spread'),
('Vegetables'),
('Vegetarian fillets'),
('Vegetarian meatloaf or patties'),
('Vegetarian stew'),
('Veggie burgers or soyburgers'),
('Vermicelli'),
('Vinegar'),
('Vinespinach'),
('Vital wheat gluten'),
('Vitasoy USA'),
('Vitasoy USA Azumaya'),
('Vitasoy USA Nasoya'),
('Vitasoy USA Organic Nasoya'),
('Vitasoy USA Organic Nasoya Sprouted'),
('WEND''YS'),
('WENDY''S'),
('WORTHINGTON Chic-Ketts'),
('WORTHINGTON Chili'),
('WORTHINGTON Choplets'),
('WORTHINGTON Diced Chik'),
('WORTHINGTON Dinner Roast'),
('WORTHINGTON FriChik Original'),
('WORTHINGTON FriPats'),
('WORTHINGTON Leanies'),
('WORTHINGTON Low Fat Fri Chik'),
('WORTHINGTON Low Fat Veja-Links'),
('WORTHINGTON Meatless Chicken Roll'),
('WORTHINGTON Meatless Corned Beef Roll'),
('WORTHINGTON Multigrain Cutlets'),
('WORTHINGTON Prime Stakes'),
('WORTHINGTON Prosage Links'),
('WORTHINGTON Prosage Roll'),
('WORTHINGTON Saucettes'),
('WORTHINGTON Smoked Turkey Roll'),
('WORTHINGTON Stakelets'),
('WORTHINGTON Stripples'),
('WORTHINGTON Super Links'),
('WORTHINGTON Vegetable Skallops'),
('WORTHINGTON Vegetable Steaks'),
('WORTHINGTON Vegetarian Burger'),
('WORTHINGTON Veja-Links'),
('WORTHINGTON Wham'),
('Waffle'),
('Waffles'),
('Walrus'),
('Wasabi'),
('Water'),
('Waterchestnuts'),
('Watercress'),
('Watermelon'),
('Waxgourd'),
('Whale'),
('Wheat'),
('Wheat bran'),
('Wheat flour'),
('Wheat flours'),
('Wheat germ'),
('Whey'),
('Whipped cream substitute'),
('Whipped topping'),
('Whiskey sour mix'),
('Wild rice'),
('Willow'),
('Wine'),
('Winged bean'),
('Winged bean leaves'),
('Winged bean tuber'),
('Winged beans'),
('Wocas'),
('Wonton wrappers'),
('Yachtwurst'),
('Yam'),
('Yambean'),
('Yardlong bean'),
('Yardlong beans'),
('Yautia'),
('Yeast extract spread'),
('Yellow rice with seasoning'),
('Yogurt'),
('Yogurt parfait'),
('Zwieback');